trunk/src/main/java/by/sjc/giz/model/Book.java
package by.sjc.giz.model;

import by.sjc.giz.model.publisher.Publisher;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Book {

    private int id;
    private String name;
    @DateTimeFormat(pattern = "dd/MM/yyyy")
    private Date releaseDate;
    private List<String> authorList;
    private List<String> genreList;
    private Publisher publisher;

    public Book() {
        init();
    }

    public Book(String name){
        init();
        this.name = name;
    }

    private void init(){
        authorList = new ArrayList<String>();
        genreList = new ArrayList<String>();
    }

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    public Publisher getPublisher() {
        return publisher;
    }
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }

    public List<String> getGenreList() {
        return genreList;
    }
    public void setGenreList(List<String> genreList) {
        this.genreList = genreList;
    }
    public void addGenre(String genre) {
        genreList.add(genre);
    }

    public List<String> getAuthorList() {
        return authorList;
    }
    public void setAuthorList(List<String> authorList) {
        this.authorList = authorList;
    }
    public void addAuthor(String author) {
        authorList.add(author);
    }

    public boolean getIsReleased() {
        return releaseDate != null && 1 > releaseDate.compareTo(new Date());
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", releaseDate=" + releaseDate +
                ", authorList=" + authorList +
                ", genreList=" + genreList +
                ", publisher=" + publisher +
                '}';
    }
}

trunk/src/main/java/by/sjc/giz/model/Order.java
package by.sjc.giz.model;

import by.sjc.giz.model.payment.Payment;

import java.util.*;

/**
 * Created by irina on 28.07.14.
 */
public class Order {

    private int id;
    private Subject sender;
    private Subject recipient;
    private List<OrderRecord> records;
    private String address;
    private Payment payment;
    private Date changeDate;
    private OrderStatus state;

    public Order() {
        records = new ArrayList<OrderRecord>();
    }

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public Subject getSender() {
        return sender;
    }
    public void setSender(Subject sender) {
        this.sender = sender;
    }

    public Subject getRecipient() {
        return recipient;
    }
    public void setRecipient(Subject recipient) {
        this.recipient = recipient;
    }

    public List<OrderRecord> getRecords() {
        return records;
    }
    public void setRecords(List<OrderRecord> records) {
        this.records = records;
    }

    public String getAddress() {
        return address;
    }
    public void setAddress(String address) {
        this.address = address;
    }

    public Payment getPayment() {
        return payment;
    }
    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    public Date getChangeDate() {
        return changeDate;
    }
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }

    public OrderStatus getState() {
        return state;
    }
    public void setState(OrderStatus state) {
        this.state = state;
    }

    public float getCost() {
        float sum = 0;
        for (OrderRecord record : records)
            sum += record.getBookPrice() * record.getCount();
        return sum;
    }

    public boolean getIsPreorder() {
        Iterator<OrderRecord> iter = records.iterator();
        while (iter.hasNext()) {
            if ( !iter.next().getBook().getIsReleased() )
                return true;
        }
        return false;
    }

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", sender=" + sender +
                ", recipient=" + recipient +
                ", records=" + records +
                ", address='" + address + '\'' +
                ", payment=" + payment +
                ", changeDate=" + changeDate +
                ", state=" + state +
                '}';
    }

    public void addBook(Book book, int count, float bookPrice) {
        this.records.add(new OrderRecord(book, count, bookPrice));
    }
}

trunk/src/main/java/by/sjc/giz/model/payment/Payment.java
package by.sjc.giz.model.payment;

import javax.validation.constraints.Size;

/**
 * Created by Z on 29.07.14.
 */
public class Payment {

    //when customer are making order, offer him his payment history.
    private int id;

    @Size(min = 1, max = 40, message = "Please, enter your id.")
    private String userIdInService;
    private PaymentMethod paymentMethod;

    public Payment() {
    }

    public Payment(String userIdInService, PaymentMethod paymentMethod) {
        this.userIdInService = userIdInService;
        this.paymentMethod = paymentMethod;
    }

    public Payment(int id, String userIdInService, PaymentMethod paymentMethod) {
        this.id = id;
        this.userIdInService = userIdInService;
        this.paymentMethod = paymentMethod;
    }

    public int getId() {
        return id;
    }

    public String getUserIdInService() {
        return userIdInService;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setUserIdInService(String userIdInService) {
        this.userIdInService = userIdInService;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @Override
    public String toString() {
        return "Payment{" +
                "id=" + id +
                ", userIdInService='" + userIdInService + '\'' +
                ", paymentMethod=" + paymentMethod +
                '}';
    }
}

trunk/src/main/java/by/sjc/giz/model/payment/PaymentMethod.java
package by.sjc.giz.model.payment;

/**
 * Created by Z on 29.07.14.
 */
public enum PaymentMethod {
    CASH, WEBMONEY, SMS;

    public String getValue() {
        return this.name();
    }
}

trunk/src/main/java/by/sjc/giz/model/payment/PaymentProcessor.java
package by.sjc.giz.model.payment;

/**
 * Created by Z on 29.07.14.
 */
public interface PaymentProcessor {
    public void paymentRequest(Payment payment, float value);
    public PaymentStatus checkPaymentStatus(Payment payment);
}

trunk/src/main/java/by/sjc/giz/model/payment/PaymentProcessorFactory.java
package by.sjc.giz.model.payment;

/**
 * Created by Z on 31.07.14.
 */
public interface PaymentProcessorFactory {
    public PaymentProcessor getPaymentProcessor(Payment payment);
}

trunk/src/main/java/by/sjc/giz/model/payment/PaymentStatus.java
package by.sjc.giz.model.payment;

/**
 * Created by Z on 28.07.14.
 */
public enum PaymentStatus {
    WAITING_FOR_USER, PAYED, DENIED
}

trunk/src/main/java/by/sjc/giz/web/controller/OrderController.java
package by.sjc.giz.web.controller;

import by.sjc.giz.model.Account;
import by.sjc.giz.model.Cart;
import by.sjc.giz.model.Order;
import by.sjc.giz.model.Subject;
import by.sjc.giz.model.SubjectType;
import by.sjc.giz.model.payment.Payment;
import by.sjc.giz.model.payment.PaymentMethod;
import by.sjc.giz.model.shop.BookInShopListWrapper;
import by.sjc.giz.security.CustomUserDetails;
import by.sjc.giz.service.OrderService;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpSession;
import javax.validation.Valid;
import java.util.List;

/**
 * Created by irina on 17.08.14.
 */
@Controller
@PreAuthorize("isFullyAuthenticated()")
@RequestMapping("/order")
public class OrderController {

    public static final Logger logger = Logger.getLogger(OrderController.class);

    @Autowired
    private OrderService orderService;

    @RequestMapping(value = "/payment", method = { RequestMethod.GET })
    public ModelAndView orderPayment(Authentication authentication) {

        logger.debug("order payment");
        ModelAndView mav = new ModelAndView();
        mav.addObject("paymentMethods", PaymentMethod.values());

        Account account = ((CustomUserDetails) authentication.getPrincipal()).getAccount();
        assert null != account;

        mav.addObject("payment", new Payment());
        if (account.getCart().getBooks().isEmpty()) {
            mav.setViewName("cart");
        } else {
            mav.setViewName("order.payment");
            mav.addObject("address", "");
        }
        return mav;
    }

    @RequestMapping(value = "/payment", method = { RequestMethod.POST })
    public ModelAndView orderPayment(HttpSession session,
                                     @Valid Payment payment,
                                     BindingResult result,
                                     @RequestParam String address) {

        ModelAndView mav = new ModelAndView();
        if (result.hasErrors() || "".equals(address.trim())) {
            mav.addObject("paymentMethods", PaymentMethod.values());
            mav.setViewName("order.payment");
            mav.addObject("message", "Enter your address");
        } else {
            session.setAttribute("payment", payment);
            session.setAttribute("address", address);
            mav.setViewName("order.confirm");
        }
        return mav;
    }

    @RequestMapping(value = "/new")
    public ModelAndView newOrder(Authentication authentication,
                                 HttpSession session) {

        logger.info("creating new order");
        ModelAndView mav = new ModelAndView();

        Account account = ((CustomUserDetails) authentication.getPrincipal()).getAccount();
        assert null != account;

        Payment payment = (Payment) session.getAttribute("payment");
        String address = (String) session.getAttribute("address");

        Subject subject = account.getSubject();
        if (subject.getType() == SubjectType.SHOP) {
            BookInShopListWrapper books =
                    orderService.makeOrderFromShopToPublisher(account, payment, address);

            if (books.getBookInShopList().size() != 0) {
                mav.addObject("books", books);
                mav.setViewName("shop.books.prices");
            } else {
                mav.setViewName("redirect:/order/outgoing");
            }
        } else {
            orderService.makeOrder(account, payment, address);
            mav.setViewName("redirect:/order/outgoing");
        }

        account.setCart(new Cart());
        session.removeAttribute("payment");
        session.removeAttribute("address");

        return mav;
    }

    @RequestMapping(value={"/incoming"})
    public ModelAndView listIncomingOrders(
            Authentication authentication ) {
        Subject subject = ((CustomUserDetails) authentication.getPrincipal()).getAccount().getSubject();

        List<Order> orders = orderService.getIncomingOrders(subject.getId());

        ModelAndView mav = new ModelAndView();
        mav.setViewName("order.list.incoming");
        mav.addObject("orders", orders);
        mav.addObject("subject", subject);

        return mav;
    }

    @RequestMapping(value={"/outgoing"})
    public ModelAndView listOutgoingOrders(
            Authentication authentication ) {
        Subject subject = ((CustomUserDetails) authentication.getPrincipal()).getAccount().getSubject();

        List<Order> orders = orderService.getOutgoingOrders(subject.getId());

        ModelAndView mav = new ModelAndView();
        mav.setViewName("order.list.outgoing");
        mav.addObject("orders", orders);
        mav.addObject("subject", subject);

        return mav;
    }

    @RequestMapping(value={"/archive/incoming"})
    public ModelAndView listArchiveIncomingOrders(
            Authentication authentication ) {
        Subject subject = ((CustomUserDetails) authentication.getPrincipal()).getAccount().getSubject();

        ModelAndView mav = new ModelAndView();

        List<Order> orders = orderService.getCompletedIncomingOrders(subject.getId());

        mav.setViewName("order.archive");
        mav.addObject("orders", orders);
        mav.addObject("subject", subject);

        return mav;
    }

    @RequestMapping(value={"/archive/outgoing"})
    public ModelAndView listArchiveOutgoingOrders(
            Authentication authentication ) {
        Subject subject = ((CustomUserDetails) authentication.getPrincipal()).getAccount().getSubject();

        ModelAndView mav = new ModelAndView();

        List<Order> orders = orderService.getCompletedOutgoingOrders(subject.getId());

        mav.setViewName("order.archive");
        mav.addObject("orders", orders);
        mav.addObject("subject", subject);

        return mav;
    }
}

trunk/src/main/webapp/WEB-INF/views/order/archive.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<table border="1" cellpadding="10" cellspacing="0" class="table table-striped table-bordered">
    <tr>
        <th>Id</th>
        <th>Sender</th>
        <th>Recipient</th>
        <th>Books</th>
        <th>Cost</th>
        <th>Address</th>
        <th>Payment</th>
        <th>State</th>
        <th>Date</th>
    </tr>

    <c:forEach items="${orders}" var="order">
        <tr id="ord${order.id}">
            <td><c:out value="${order.id}" /></td>
            <td><c:out value="${order.sender.name}"/></td>
            <td><c:out value="${order.recipient.name}"/></td>
            <td>
                <table border=1 class="table table-striped table-bordered">
                    <tr>
                        <th>book id</th>
                        <th>name</th>
                        <th>authors</th>
                        <th>released</th>
                        <th>count</th>
                        <th>book price</th>
                    </tr>
                    <c:forEach items="${order.records}" var="record">
                        <c:set var="book" value="${record.book}" />
                        <tr valign="center" id="ord${order.id}bk${book.id}">
                            <td><c:out value="${book.id}"/></td>
                            <td><a href='#'><c:out value="${book.name}" /></a></td>
                            <td><c:out value="${book.authorList}" /></td>
                            <td><c:out value="${book.isReleased}"/> </td>
                            <td><c:out value="${record.count}"/></td>
                            <td><c:out value="${record.bookPrice}"/></td>
                        </tr>
                    </c:forEach>
                </table>
            </td>
            <td><c:out value="${order.cost}"/></td>
            <td><c:out value="${order.address}"/></td>
            <td>
                <%--order info--%>
                <table border="1" class="table table-striped table-bordered">
                    <tr>
                        <td>id</td>
                        <td><c:out value="${order.payment.id}"/></td>
                    </tr>
                    <tr>
                        <td>method</td>
                        <td><c:out value="${order.payment.paymentMethod}" /></td>
                    </tr>
                    <tr>
                        <td>user id in service</td>
                        <td><c:out value="${order.payment.userIdInService}" /></td>
                    </tr>
                </table>
            </td>
            <td>
                <c:out value="${order.state}"/>
            </td>
            <td>
                <c:out value="${order.changeDate}"/>
            </td>

        </tr>
    </c:forEach>
</table>

trunk/src/main/webapp/WEB-INF/views/order/confirm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core_rt" %>
<c:set var="principal" value="${pageContext.request.userPrincipal.principal}" />
<c:set value="${principal.account}" var="account" />
<h3>Confirm order</h3>

<table border="1" class="table table-striped table-bordered">
    <tr>
        <th>Name</th>
        <th>Authors</th>
        <%--<th>Price</th>--%>
        <th>Count</th>
    </tr>
    <c:forEach items="${account.cart.books}" var="bookInCart">
        <c:set var="book" value="${bookInCart.book}" />
        <tr>
            <td>${book.name}</td>
            <td>${book.authorList}</td>
            <%--<td>${book.sellPrice}</td>--%>
            <td>${bookInCart.count}</td>
        </tr>
    </c:forEach>
</table>
<br/>
<p>Payment method: ${payment.paymentMethod.value}</p>
<br/>
<p>ID: ${payment.userIdInService}</p>
<br/>
<p>Address: ${address}</p>
<br/>
<a href="<c:url value='/order/payment'/>" class="btn btn-primary" role="button">back</a>
<a href="<c:url value='/order/new'/>" class="btn btn-success" role="button">Yes, I want to buy it!</a>

trunk/src/main/webapp/WEB-INF/views/order/list-incoming.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>



<script type="text/javascript" >
    function rejectBook(orderId, bookId) {
        $.post(
                "<c:url value='/order/ajax/rejectBookFromIncomingOrder'/>",
                { orderId: orderId, bookId: bookId }
        ).success(
                function(orders) {
                    console.info("returned orders");
                    console.info(orders);
                    $("#ord"+orderId).after(ordersToStr(orders)).remove();
                }
        ).error(
                function() {
                    alert("error");
                }
        );
    }

    function rejectOrder(orderId) {
        $.post(
                "<c:url value='/order/ajax/rejectIncomingOrder'/>",
                { orderId: orderId }
        ).success(
                function(order) {
                    console.info("returned order");
                    console.info(order);
                    $("#ord"+orderId).after(orderToStr(order)).remove();
                }
        ).error(
                function() {
                    alert("error");
                }
        );
    }
    function confirmOrder(orderId) {
        $.post(
                "<c:url value='/order/ajax/confirmIncomingOrder'/>",
                { orderId : orderId }
        ).success(
                function(order) {
                    console.info("returned order");
                    console.info(order);
                    $("#ord"+orderId).after(orderToStr(order)).remove();
                }
        ).error(
                function() {
                    alert("error");
                }
        );
    }

    function ordersToStr(orders) {
        res = "";
        for (i in orders) {
            res += orderToStr(orders[i]);
        }
        return res;
    }

    function orderToStr(order) {
        var res = "<tr id='ord" + order.id + "'>" +
                "<td>" + order.id + "</td>" +
                "<td>" + order.sender.name + "</td>" +
                "<td>" + order.recipient.name + "</td>" +
                "<td>" + recordsToStr(order) + "</td>" +
                "<td>" + order.cost + "</td>" +
                "<td>" + order.address + "</td>" +
                "<td>" + paymentToStr(order.payment) + "</td>" +
                "<td>" + order.isPreorder + "</td>" +
                "<td>" + order.state + "</td>" +
                "<td>" + order.changeDate + "</td>" +
                "<td>" + deriveHandlersStr(order) +"</td>" +
              "</tr>";
        return res;
    }

    function recordsToStr(order) {
        var records = order.records;
        var res = '<table border=1 class="table table-striped table-bordered">'+
        '<thead>' +
        '<th>name</th>'+
        '<th>authors</th>'+
        '<th>released</th>'+
        '<th>count</th>'+
        '<th>book price</th>';

        if (canReject(order))
            res += '<th>reject</th>';

        res += '</thead>'+

        '<tbody>';

        <c:url value="/book/" var="bookBaseUrl"/>
        for (var i in records) {
            var record = records[i];
            var book = record.book;

            res += '<tr valign="center" id="ord' + order.id + 'bk' + book.id + '">' +
            '<td><a href="${bookBaseUrl}'+book.id+'">'+book.name+'</a></td>' +
            '<td>'+book.authorList+'</td>' +
            '<td>'+book.isReleased+'</td>' +
            '<td>'+record.count+'</td>' +
            '<td>'+record.bookPrice;
            if (canReject(order.state))
                res += '<input type="button" value="reject" onclick="rejectBook('+order.id+','+book.id+')" />';
            res += '</td></tr>';
        }

        res += '</tbody>' +
                '</table>';
        return res;
    }

    function paymentToStr(payment) {
        var res = '<table border="1" class="table table-striped table-bordered">'+
            '<tr>'+
                '<td>id</td>'+
                '<td>'+payment.id+'</td>'+
            '</tr>'+
            '<tr>'+
                '<td>method</td>'+
                '<td>'+payment.paymentMethod+'</td>'+
            '</tr>'+
            '<tr>'+
                '<td>user id in service</td>'+
                '<td>'+payment.userIdInService+'</td>'+
            '</tr>'+
        '</table>';
        return res;
    }

    function deriveHandlersStr(order) {
        var res =""
        if (order.state=='NEW')
            res = '<input type="button" value="accept" onclick="confirmOrder(' + order.id + ')" />';
        if (order.state=='WAITING_FOR_BOOK_RELEASES')
            res = '<input type="button" value="check book releases" onclick="confirmOrder(' + order.id + ')" />';
        if (order.state=='WAITING_FOR_RECIPIENT_FEASIBILITY')
            res = '<input type="button" value="check feasibility" onclick="confirmOrder(' + order.id + ')" />';
        if (order.state=='WAITING_FOR_PAY')
            res = '<input type="button" value="check user pay" onclick="confirmOrder(' + order.id + ')" />';
        if (order.state=='SENDER_CANCELED')
            res = '<input type="button" value="okay" onclick="confirmOrder(' + order.id + ')" />';

        if (canReject(order.state))
            res += '<input type="button" value="reject" onclick="rejectOrder(' + order.id + ')" />';
        return res;
    }

    function canReject(orderState) {
        return (orderState=='NEW' ||
                orderState=='WAITING_FOR_BOOK_RELEASES' ||
                orderState=='WAITING_FOR_RECIPIENT_FEASIBILITY');
    }
</script>

<h3>"${subject.name}" incoming orders</h3>

<br/><br/>
<table id="orderTable" border="1" cellpadding="10" cellspacing="0" class="table table-striped table-bordered">
    <thead>
        <th>Id</th>
        <th>Sender</th>
        <th>Recipient</th>
        <th>Books</th>
        <th>Cost</th>
        <th>Address</th>
        <th>Payment</th>
        <th>is pre order</th>
        <th>State</th>
        <th>Date</th>
        <th>Handle</th>
    </thead>

    <tbody>
    <c:forEach items="${orders}" var="order">
        <c:if test="${order.state=='NEW' or
                                order.state=='WAITING_FOR_BOOK_RELEASES' or
                                order.state=='WAITING_FOR_RECIPIENT_FEASIBILITY'}"
              var="canReject" />

        <tr id="ord${order.id}">
            <td><c:out value="${order.id}" /></td>
            <td><c:out value="${order.sender.name}"/></td>
            <td><c:out value="${order.recipient.name}"/></td>
            <td>
                <table border=1 class="table table-striped table-bordered">

                    <thead>
                        <th>name</th>
                        <th>authors</th>
                        <th>released</th>
                        <th>count</th>
                        <th>book price</th>
                        <c:if test="${canReject}"><th>reject book</th></c:if>
                    </thead>

                    <tbody>
                    <c:forEach items="${order.records}" var="record">
                        <c:set var="book" value="${record.book}" />
                        <tr valign="center" id="ord${order.id}bk${book.id}">
                            <td><a href='<c:url value="/book/${book.id}"/>'><c:out value="${book.name}" /></a></td>
                            <td><c:out value="${book.authorList}" /></td>
                            <td><c:out value="${book.isReleased}"/> </td>
                            <td><c:out value="${record.count}"/></td>
                            <td><c:out value="${record.bookPrice}"/></td>
                            <c:if test="${canReject}">
                                <td>
                                    <input type="button" value="reject" onclick="rejectBook(${order.id},${book.id})" />
                                </td>
                            </c:if>
                        </tr>
                    </c:forEach>
                    </tbody>

                </table>
            </td>
            <td><c:out value="${order.cost}"/></td>
            <td><c:out value="${order.address}"/></td>
            <td>
                    <%--order info--%>
                <table border="1" class="table table-striped table-bordered">
                    <tr>
                        <td>id</td>
                        <td><c:out value="${order.payment.id}"/></td>
                    </tr>
                    <tr>
                        <td>method</td>
                        <td><c:out value="${order.payment.paymentMethod}" /></td>
                    </tr>
                    <tr>
                        <td>user id in service</td>
                        <td><c:out value="${order.payment.userIdInService}" /></td>
                    </tr>
                </table>
            </td>
            <td>
                <c:out value="${order.isPreorder}"/>
            </td>
            <td>
                <c:out value="${order.state}"/>
            </td>
            <td>
                <c:out value="${order.changeDate}"/>
            </td>
            <td>
                <%--confirming order--%>
                <c:choose>
                    <c:when test="${order.state=='NEW'}">
                        <input type="button" value="accept" onclick="confirmOrder(${order.id})" />
                    </c:when>
                    <c:when test="${order.state=='WAITING_FOR_BOOK_RELEASES'}">
                        <input type="button" value="check book releases" onclick="confirmOrder(${order.id})" />
                    </c:when>
                    <c:when test="${order.state=='WAITING_FOR_RECIPIENT_FEASIBILITY'}">
                        <input type="button" value="check feasibility" onclick="confirmOrder(${order.id})" />
                    </c:when>
                    <c:when test="${order.state=='WAITING_FOR_PAY'}">
                        <input type="button" value="check user pay" onclick="confirmOrder(${order.id})" />
                    </c:when>
                    <c:when test="${order.state=='SENDER_CANCELED'}">
                        <input type="button" value="okay" onclick="confirmOrder(${order.id})" />
                    </c:when>
                </c:choose>

                <c:if test="${canReject}">
                    <input type="button" value="reject" onclick="rejectOrder(${order.id})" />
                </c:if>

            </td>

        </tr>
    </c:forEach>
    </tbody>
</table>

trunk/src/main/webapp/WEB-INF/views/order/payment.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div class="form-group col-lg-4">
    <h3>Payment method</h3>
    <c:url value="/order/payment" var="actionUrl" />
    <form:form action="${actionUrl}" commandName="payment" modelAttribute="payment" method="POST">

        <form:select path="paymentMethod" class="form-control">
            <c:forEach items="${paymentMethods}" var="method">
                <form:option value="${method.value}">${method.value}</form:option>
            </c:forEach>
        </form:select>
        <br/>
        <form:input path="userIdInService" placeholder="User ID in service" class="form-control"/>
        <form:errors path="userIdInService"/>
        <br/>
        <h3>Address</h3>
        <input type="text" name="address" placeholder="Address" class="form-control"/>
        <p>${message}</p>
        <br/>
        <a href="<c:url value='/cart/'/>" class="btn btn-primary" role="button">back</a>
        <input type="submit" value="confirm" class="btn btn-success"/>
    </form:form>
</div>